# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('gst_registered_no', models.CharField(max_length=100)),
                ('uen_acra', models.IntegerField()),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(choices=[('INGAPORE', 'INGAPORE'), ('MALAYSIA', 'MALAYSIA'), ('INDONESIA', 'INDONESIA'), ('AUSTRALIA', 'AUSTRALIA'), ('VIETNAM', 'VIETNAM'), ('CAMBODIA', 'CAMBODIA'), ('THAILAND', 'THAILAND'), ('PHILLIPINES', 'PHILLIPINES')], default='VIETNAM', max_length=100)),
                ('cus_type', models.CharField(choices=[('1', 'RESIDENTIAL'), ('2', 'COMMERCIAL'), ('3', 'INDUSTRIAL'), ('4', 'GOVERNMENTAL'), ('5', 'N/A')], default='5', max_length=100)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
