
code = {
    'OK_LOGIN' : 'Login successfully',
    'OK_LOGOUT' : 'Logout successfully',
    'OK_REGISTRATION' : 'Register successfully',
    'OK_SEND_EMAIL' : 'We just sent you the link to your email',
    'OK_RESET_PASSWORD' : 'Reset password successfully',
    'OK_CHANGE_PASSWORD': 'Change password successfully',
    'OK_SEND_FRIEND_REQUEST': 'Friend request sent successfully',
    'OK_ACCEPT_FRIEND_REQUEST': 'Friend request has been accepted successfully',
    'OK_REJECT_FRIEND_REQUEST': 'Reject friend request successfully',
    'OK_CANCEL_FRIEND_REQUEST': 'Cancel friend request successfully',
    'OK_UNFRIEND': 'Unfriend successfully',
    'OK_SEARCH': 'Return search data successfully',
    'OK_SUGGESTION' : 'Return suggestion data successfully',
    'OK_LIKE': 'Save like successfully',
    'OK_UNLIKE': 'Unlike successfully',
    'OK_SHARE': 'Share successfully',

    'E_NOT_ACTIVE': 'Your account is not active',
    'E_LOGIN_INCORRECT' : 'The email or password that you entered is incorrect',
    'E_IS_LOGIN' :'You are already log in',
    'E_IS_NOT_LOGIN': 'You are not log in',
    'E_SEND_EMAIL_FAIL' : 'There are problems in sending email. Please try again',
    'E_INVALID_PARAMETER_VALUES': 'Request invalid, please verify the parameter',
    'E_USER_NOT_FOUND' : 'User can not be found',
    'E_INVALID_ACTIVATE_KEY': 'Your activation key is invalid',
    'E_DUPLICATE_EMAIL': 'The email has been used already',
    'E_DUPLICATE_USERNAME': 'The username has been used already',
    'E_INVALID_EMAIL': 'The email is not valid',
    'E_INVALID_PASSWORD': 'The password must be at least 8 characters long',
    'E_PASSWORD_MISMATCH': 'Password confirmation mismatch',
    'E_EMAIL_NOT_FOUND': 'Email address not verified for any user account',
    'E_SAME_USER': 'Error when user sends request to himself',
    'E_ALREADY_SEND_REQUEST': 'Error when user has already sent request',
    'E_ALREADY_CONNECT': 'User has already connected with another user',
    'E_ALREADY_EXIST': 'This item is already existed',
    'E_NOT_CREATED': 'Cannot create in database',
    'E_REQUEST_NOT_FOUND': 'Cannot find this request',
    'E_POST_NOT_FOUND' : 'Cannot find this post',
    'E_NOT_FOUND':'The requested resource is not found',
    'E_NOT_SAVE': 'Cannot save to database',
    'E_GET_NOT_ALLOW': 'Reject a get request to retrieve user profile or something else...',

}